name: Python Tests and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        cd youtube-playlist-downloader
        uv sync --extra dev

    - name: Run tests with pytest and coverage
      run: |
        cd youtube-playlist-downloader
        uv run pytest tests --cov=. --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./youtube-playlist-downloader/coverage.xml
        flags: unittests
        slug: siavashyj/toolbox
        fail_ci_if_error: true
